using Xunit;

namespace BanquetHallManagement.EntityFrameworkCore;

[CollectionDefinition(BanquetHallManagementTestConsts.CollectionDefinitionName)]
public class BanquetHallManagementEntityFrameworkCoreCollection : ICollectionFixture<BanquetHallManagementEntityFrameworkCoreFixture>
{

}
